# Generated by Django 5.0.4 on 2024-04-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.gasto')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.gasto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.mes')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.tipogasto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.ingreso')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.mes')),
                ('tipo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.tipoingreso')),
            ],
        ),
    ]
